### ISSUE TITLE
How can I implement countries and cities?

### ISSUE THREAD

**Issue by songproducer** [inoks/django-classified#23]
I've tried doing it with groups but then I'd need to create the same section for each city multiple times - a cumbersome task.

**Comment by inoks** [comment]
This feature is currently not implemented. 
I think the best way is to create extra models for Country/City and add it as extra fields to the `Item` models.

**Comment by inoks** [comment]
Hi @songproducer !
I added Areas which you can use now to separate items while having the same Section/Group structure!
