### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by dkbast** [inoks/django-classified#25]
Hi! 
I would like to contribute to the german translation, can you please accept my request on transifex?
Thanks,
Damian

**Comment by inoks** [comment]
@dkbast Sure, just accepted! 
I may need to update translation files before, so I keep this issue open for a while.
Thank you!

**Comment by inoks** [comment]
@dkbast Thank you!
I just released new version 0.8.5 with new translations files added (German as well!)

**Comment by inoks** [comment]
@dkbast https://github.com/inoks/django-classified/blob/master/django_classified/locale/de/LC_MESSAGES/django.po#L6
