### ISSUE TITLE
Not working with Python 3

### ISSUE THREAD

**Issue by Burnsedia** [inoks/django-classified#32]

**Comment by inoks** [comment]
@Burnsedia Can you please provide more details on what does not works for you with Python 3 (Idealy PR with the failed TestCase)?
Thanks!

**Comment by Burnsedia** [comment]
I need a tutorial on how to properly install Django-Classified, Every time I pip install and config all dependencies I get an error message, ps this is my first Django projects. I usually use Flask

**Comment by Burnsedia** [comment]
I am getting an error with Django.core.exsecptions.Improperlyconfiged. Again this is my first Django project.  I am still learning Web development, coming from a C# Xamerin Native Stack.

**Comment by inoks** [comment]
Please take a look at the demo project https://github.com/inoks/django-classified-demo
