### ISSUE TITLE
Having big challenges to start using this project

### ISSUE THREAD

**Issue by imvieira** [inoks/django-classified#40]
Hi there,

Actually I am having big challenges to start using this project. I have a few questions:
- Should I use heroku ?
- how can I start the django-classified?
- should I configure something else before start using django-classified? For example, some postgre databse, configure some key?

Thank you a lot... @inoks

**Comment by inoks** [comment]
@imvieira Please check demo project [here](https://github.com/inoks/django-classified-demo).
